"""replace flw columns with momo columns

Revision ID: 24dee344ed03
Revises: 
Create Date: 2026-04-03 15:38:46.137298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dee344ed03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('momo_reference_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('momo_transaction_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('flw_payment_link')
        batch_op.drop_column('flw_transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flw_transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('flw_payment_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('momo_transaction_id')
        batch_op.drop_column('momo_reference_id')

    # ### end Alembic commands ###
